
project_id = "sqervhhkkbkidnwspuvj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.delete-user]
verify_jwt = true

[functions.insert-user-permission]
verify_jwt = true

[functions.update-user-permission]
verify_jwt = true
